<a href="https://colab.research.google.com/github/Fareeha10/Class1_Quater2_PIAIC/blob/master/numpy_class1q2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:

a = [1,12,21,33,4,3,45,23,5,6]

In [3]:
%time
res= []
for i in a:
  res.append(i*5)
res

[5, 60, 105, 165, 20, 15, 225, 115, 25, 30]

In [0]:
import numpy as np

In [0]:
a = np.array([1,12,21,33,4,3,45,23,5,6])  #alternative to previous method

In [12]:
a*5

array([  5,  60, 105, 165,  20,  15, 225, 115,  25,  30])

In [0]:
numpyArray = np.array([22,34,43,21], dtype=np.int8)   #dtype data type here we convert int to flost viceversa
#32 bits   through np. we don't write it in string it ok

In [22]:
print(type(numpyArray)) 
(numpyArray)

<class 'numpy.ndarray'>


array([22, 34, 43, 21], dtype=int8)

In [24]:
randomArr = np.random.randint(10) # here int 
randomArr

3

In [25]:
randomArr = np.random.randn(10)*10 # here equal distribution 
randomArr #result is vectors

array([  7.70692448,  -0.4200601 ,   6.02449319,  13.08200523,
         2.31961042, -12.02390867,  -5.54712454,  -6.32535677,
        -2.18931587,  -2.38007436])

In [26]:
randomArr.ndim #demension of vector

1

In [27]:
randomArr.shape

(10,)

In [31]:
twoD = np.array([[3,2,4],[1,2,3],[4,8,0],[9,7,6]])
twoD

array([[3, 2, 4],
       [1, 2, 3],
       [4, 8, 0],
       [9, 7, 6]])

In [29]:
twoD.shape

(4, 3)

In [0]:
zeroD = np.array(100)

In [34]:
zeroD.ndim  #scalar quatity

0

In [35]:
zeroD.shape

()

In [42]:
miscD = np.array([[[[99]]]]) 
print(miscD)
print(miscD.ndim)
print(miscD.shape)

[[[[99]]]]
4
(1, 1, 1, 1)


In [44]:
a = np.arange(12).reshape(4,3) # in numpy range = arange
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [0]:
flat = np.ravel(a)

In [46]:
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
flat = flat.reshape(12)

In [49]:
flat

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
ez = a.reshape(3,4)

In [77]:
ez

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [0]:
r= np.ravel(ez)

In [55]:
r

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [0]:
twD = np.arange(36).reshape(6,6)

In [59]:
twD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [0]:
threeD = twD.reshape(3,3,4)

In [61]:
threeD

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]],

       [[24, 25, 26, 27],
        [28, 29, 30, 31],
        [32, 33, 34, 35]]])

In [0]:
backtwD = threeD.reshape(6,6)  #give same reshape parameters

In [63]:
backtwD

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [0]:
new3D = np.array([[[1,2,1],[4,5,3],[9,0,9]],[[9,5,6],[5,4,3],[0,8,7]]])

In [71]:
new3D

array([[[1, 2, 1],
        [4, 5, 3],
        [9, 0, 9]],

       [[9, 5, 6],
        [5, 4, 3],
        [0, 8, 7]]])

In [0]:
#[[elements]] 2d
#[[[elements]]] 3d

In [0]:
# no need for if else in numpy

In [0]:
#to add tensor for that shape must be same

In [0]:
#if shape is different
m1 = np.arange(12).reshape(4,3)

In [0]:
m2 = np.random.randn(12).reshape(4,3)

In [80]:
m1+m2

array([[-2.08466385,  2.41545949,  3.94943851],
       [ 3.89584457,  5.48059253,  5.94190765],
       [ 6.71831912,  6.85402309,  9.13229097],
       [ 7.62705571, 10.17037222, 10.33234471]])

In [81]:
m1-m2

array([[ 2.08466385, -0.41545949,  0.05056149],
       [ 2.10415543,  2.51940747,  4.05809235],
       [ 5.28168088,  7.14597691,  6.86770903],
       [10.37294429,  9.82962778, 11.66765529]])

In [82]:
m1/m2

array([[ -0.        ,   0.70648437,   1.02593644],
       [  3.34879521,   2.70162108,   5.30837605],
       [  8.35283347, -47.95279048,   7.06532174],
       [ -6.55525506,  58.69501427, -16.4755678 ]])

In [83]:
m1*m2

array([[ -0.        ,   1.41545949,   3.89887702],
       [  2.68753371,   5.92237013,   4.70953824],
       [  4.30991473,  -1.02183834,   9.05832775],
       [-12.35649861,   1.70372222,  -7.34420819]])

In [0]:
#to * tensors check no of column and row
# 1st row should be same to 1st column

In [0]:
m3 = np.arange(18).reshape(3,6)

In [89]:
m3

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [90]:
#if m1 * m3 possible viceversa not
m1@m3

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [0]:
#mirror * is when both tensors are same and use * sign

In [92]:
np.dot(m1,m3)  #creating dot product ans is same as *

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [93]:
m1.dot(m3)

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342]])

In [95]:
zeeeros = np.zeros(4, dtype= 'int8')
zeeeros

array([0, 0, 0, 0], dtype=int8)

In [0]:
ones = np.ones((5,5), dtype= 'int8')

In [106]:
ones

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int8)

In [0]:
zeeeros = np.zeros((4,4), dtype= 'int8')

In [101]:
zeeeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int8)

In [107]:
s =ones*7
s

array([[7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7],
       [7, 7, 7, 7, 7]], dtype=int8)

In [0]:
fulll = np.full((4,4),100)

In [109]:
fulll

array([[100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100],
       [100, 100, 100, 100]])

In [0]:
emptyy = np.empty((4,4,4))

In [112]:
emptyy #shows garbege values

array([[[1.94185980e-316, 2.79437461e+276, 1.27378631e+074,
         2.63044058e+180],
        [2.57726435e-312, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000]],

       [[0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
         0.00000000e+000],
        [0.00000000e+000, 0.00000000e+0

In [113]:
m3


array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [0]:
like = np.zeros_like(m3)

In [115]:
like #like takes shape and datatype of a tensor and change them to zeros

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [0]:
i =np.eye(3,3) #identity matrix have diagonal as 1 and its determinant as 1 as well

In [120]:
#astype changes datatype
y = i.astype("int")
y

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [0]:
alist = [90,86,87,45]

In [122]:
type(alist[0])

int

In [123]:
type(alist[0:3])

list

In [124]:
#indexing and slicing on numpy
#2D index and slice
t2darr = np.arange(36).reshape(6,6)
t2darr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [125]:
t2darr[3,2] #2dindexing 

20

In [126]:
t2darr [3][2]  #2dindexing 

20

In [129]:
#slicing
t2darr[2:5,1:4] 
#/ [] into 2 parts [row,column]
#[start:end, start:end]

array([[13, 14, 15],
       [19, 20, 21],
       [25, 26, 27]])

In [130]:
t2darr[5:,3:4] #here ans is 2d 

array([[33]])

In [131]:
t2darr[]

array([[ 6,  7],
       [12, 13],
       [18, 19],
       [24, 25]])